// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/Cards.vue')['default']
    CardsHomePage: typeof import('./src/components/CardsHomePage.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LocateMap: typeof import('./src/components/LocateMap.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    OurServicesCardsHomePage: typeof import('./src/components/OurServicesCardsHomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesCards: typeof import('./src/components/ServicesCards.vue')['default']
    SixCards: typeof import('./src/components/SixCards.vue')['default']
    SixCardsHomePage: typeof import('./src/components/SixCardsHomePage.vue')['default']
    TabsMenu: typeof import('./src/components/TabsMenu.vue')['default']
  }
}
